spring.application.name=cards_api
spring.datasource.url=jdbc:postgresql://localhost:5432/cards
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cards_api.app.secret=qwerty123
cards_api.app.expirationMs=60000
